version: "3.8"
services:
  server:
    volumes:
      - ./server/bin:/home/appuser
    env_file:
      - ./server/.env--local-development
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    volumes:
      - ./frontend/public:/usr/share/nginx/html
  y_websocket_provider:
    volumes:
      - ./y_websocket_provider:/y_websocket_provider
