version: "3.8"
services:
  db:
    container_name: db
    build: ./db
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: server
    build: ./server
    volumes:
      - /usr/share/codeconnected/code_runner/client_tls_certificates:/code_runner_certs
    env_file:
      - ./server/.env
    restart: always
    depends_on:
      - "db"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "127.0.0.1:5000:80"
    depends_on:
      - "server"
    restart: always
  y_websocket_provider:
    container_name: y_websocket_provider
    build: ./y_websocket_provider
volumes:
  pgdata:
