version: "3.8"
services:
  server:
    volumes:
      - ./server/bin:/home/appuser
  frontend:
    volumes:
      - ./frontend/public:/usr/share/nginx/html
  y_websocket_provider:
    volumes:
      - ./y_websocket_provider:/y_websocket_provider
