version: "3.8"
services:
  server:
    container_name: server
    build: ./server
    volumes:
      - /usr/share/codeconnected/code_runner/client_tls_certificates:/code_runner_certs
    env_file:
      - ./server/.env
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "127.0.0.1:5000:80"
    depends_on:
      - "server"
    restart: always
